[package]
name = "aoc_day5"
version = "0.1.0"
authors = ["Diego <d.alonso-alvarez@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
