name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        for d in */
        do
          cargo build --verbose --manifest-path $d/Cargo.toml
        done
    - name: Run tests
      run: |
        for d in */
        do
          cargo test --verbose --manifest-path $d/Cargo.toml
        done
